services:
  aj-webui:
    build: .
    container_name: aj-webui
    network_mode: bridge
    ports:
      - "3000:3000"
      - "3001:3001"  # Proxy Server
      - "5173:5173"  # Vite Development Server
    environment:
      - NODE_ENV=production
      - VITE_AJ_CORE_HOST=192.168.178.222
      - VITE_AJ_CORE_PORT=9854
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:3000/status', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
