services:
  aj-webui:
    build: .
    container_name: aj-webui
    network_mode: bridge
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    #  - VITE_AJ_CORE_HOST=localhost
    #  - VITE_AJ_CORE_PORT=9851
      - PORT=3000
      - DISABLE_AUTO_UPDATE=false # Auf 'true' setzen, um automatische Updates zu deaktivieren
    restart: unless-stopped
    command:
      - npm
      - run
      - start
