services:
  aj-webui:
    build: .
    container_name: aj-webui
    network_mode: bridge
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite Development Server
    environment:
      - NODE_ENV=production
      - VITE_AJ_CORE_HOST=192.168.178.222
      - VITE_AJ_CORE_PORT=9854
      - PORT=3000
    restart: unless-stopped
