services:
  aj-webui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aj-webui-dev
    network_mode: bridge
    ports:
      - "5173:5173"  # Vite Development Server
      - "3001:3001"  # Proxy Server
      - "3000:3000"  # Backup/Admin Server
    volumes:
      - /mnt/volume1/hs-webspace/www/aj-webui:/app
      - /app/node_modules
      - /app/.vite  # Vite cache ausschließen
    environment:
      - NODE_ENV=development
      - VITE_AJ_CORE_HOST=192.168.178.222
      - VITE_AJ_CORE_PORT=9854
      - VITE_DEV_SERVER_PORT=5173
      - PROXY_PORT=3001
    restart: unless-stopped
    stdin_open: true
    tty: true
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "curl -f http://localhost:3001/api/settings.xml?password=test >/dev/null 2>&1 && curl -f http://localhost:5173 >/dev/null 2>&1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
