
version: '3.8'
services:
  aj-webui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aj-webui-dev
    network_mode: bridge
    ports:
      - "5173:5173"  # Vite Development Server
      - "3000:3000"  # Backup/Admin Server
    volumes:
      - /mnt/volume1/hs-webspace/www/aj-webui:/app
      - /app/node_modules
      - /app/.vite  # Vite cache ausschließen
    environment:
      - NODE_ENV=development
      - VITE_AJ_CORE_HOST=192.168.178.222
      - VITE_AJ_CORE_PORT=9854
      - VITE_DEV_MODE=true
      - DISABLE_AUTO_UPDATE=true
    restart: unless-stopped
    stdin_open: true
    tty: true
